[[libidn2]]
arch = "aarch64"
git-tree-sha1 = "5caa9ff4641687171e71556edc21b4be2d803f4b"
os = "macos"

    [[libidn2.download]]
    sha256 = "b7671a5b7efe161f58b09fe8cb5d22ba1d8ae0fde3693030fc4b7b386063f627"
    url = "https://github.com/JuliaBinaryWrappers/libidn2_jll.jl/releases/download/libidn2-v2.3.8+0/libidn2.v2.3.8.aarch64-apple-darwin.tar.gz"
[[libidn2]]
arch = "aarch64"
git-tree-sha1 = "4d0386e207c5bde5f3189b1d7d8ddae82a4b8b66"
libc = "glibc"
os = "linux"

    [[libidn2.download]]
    sha256 = "83b002ea1b49fb596582e69f076df2889ece29c48252b2f59651befe0507e4fe"
    url = "https://github.com/JuliaBinaryWrappers/libidn2_jll.jl/releases/download/libidn2-v2.3.8+0/libidn2.v2.3.8.aarch64-linux-gnu.tar.gz"
[[libidn2]]
arch = "aarch64"
git-tree-sha1 = "46330c72f5c779fe4c81d5368340b02ed7ca5d28"
libc = "musl"
os = "linux"

    [[libidn2.download]]
    sha256 = "da3650ebc58fb0533607ff7e9eec26c61d4c0910e7f3931e97a8990aae90ef19"
    url = "https://github.com/JuliaBinaryWrappers/libidn2_jll.jl/releases/download/libidn2-v2.3.8+0/libidn2.v2.3.8.aarch64-linux-musl.tar.gz"
[[libidn2]]
arch = "aarch64"
git-tree-sha1 = "95702fc8a42e363effcfeba748bb8a752b68f77f"
os = "freebsd"

    [[libidn2.download]]
    sha256 = "3ead1258b4a7d9f2feb05349354f08ad27e5766deb39d9b554887ce981094bde"
    url = "https://github.com/JuliaBinaryWrappers/libidn2_jll.jl/releases/download/libidn2-v2.3.8+0/libidn2.v2.3.8.aarch64-unknown-freebsd.tar.gz"
[[libidn2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a0ea4047385b5ad2c67e442b0808daeb1c116efb"
libc = "glibc"
os = "linux"

    [[libidn2.download]]
    sha256 = "fa54e33332885af72bdc58136a9c053c6b6ea2625b1bb5d0fd05ceec113fb64c"
    url = "https://github.com/JuliaBinaryWrappers/libidn2_jll.jl/releases/download/libidn2-v2.3.8+0/libidn2.v2.3.8.armv6l-linux-gnueabihf.tar.gz"
[[libidn2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "982f8b6ccca4d9027765972c6de10e6790f5cad1"
libc = "musl"
os = "linux"

    [[libidn2.download]]
    sha256 = "ede57fcda49cddbb25827abda789be520fd585cc3fb9ebdb66df92a80f7b829b"
    url = "https://github.com/JuliaBinaryWrappers/libidn2_jll.jl/releases/download/libidn2-v2.3.8+0/libidn2.v2.3.8.armv6l-linux-musleabihf.tar.gz"
[[libidn2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "eb64ddd475675fbe7b8824c0264887ca4849fbb6"
libc = "glibc"
os = "linux"

    [[libidn2.download]]
    sha256 = "0143494d61a6a296e4b9047d31312ddb10bd60e2a6a42898d02ba344909d7364"
    url = "https://github.com/JuliaBinaryWrappers/libidn2_jll.jl/releases/download/libidn2-v2.3.8+0/libidn2.v2.3.8.armv7l-linux-gnueabihf.tar.gz"
[[libidn2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "32af7a5aa99b7d3ed60328cd68fe66f9529ec1be"
libc = "musl"
os = "linux"

    [[libidn2.download]]
    sha256 = "33040046ef25c95f88b2d639497510d9f40dbfa13475aa0751c1226ef51d5a44"
    url = "https://github.com/JuliaBinaryWrappers/libidn2_jll.jl/releases/download/libidn2-v2.3.8+0/libidn2.v2.3.8.armv7l-linux-musleabihf.tar.gz"
[[libidn2]]
arch = "i686"
git-tree-sha1 = "00ffb742cc82e261267d8488683eaa6ce16bf158"
libc = "glibc"
os = "linux"

    [[libidn2.download]]
    sha256 = "d3d66bd1caef873d79c21cc260e3f074fa6b2b44a63d7e959edf2528d481adad"
    url = "https://github.com/JuliaBinaryWrappers/libidn2_jll.jl/releases/download/libidn2-v2.3.8+0/libidn2.v2.3.8.i686-linux-gnu.tar.gz"
[[libidn2]]
arch = "i686"
git-tree-sha1 = "65f04342d74b9b96cad9ea397709ac611c737482"
libc = "musl"
os = "linux"

    [[libidn2.download]]
    sha256 = "47be9e2bd390642f9a045b131c1894ddbf1a98990077f0f0a5307ea77b555d7b"
    url = "https://github.com/JuliaBinaryWrappers/libidn2_jll.jl/releases/download/libidn2-v2.3.8+0/libidn2.v2.3.8.i686-linux-musl.tar.gz"
[[libidn2]]
arch = "i686"
git-tree-sha1 = "95a20dab94b3b437ae098e498ad77b3324ac4751"
os = "windows"

    [[libidn2.download]]
    sha256 = "0ba5942b7636dd8c06e42f62b8bd578ef442aabaaf422be69e101cc7a99032ca"
    url = "https://github.com/JuliaBinaryWrappers/libidn2_jll.jl/releases/download/libidn2-v2.3.8+0/libidn2.v2.3.8.i686-w64-mingw32.tar.gz"
[[libidn2]]
arch = "powerpc64le"
git-tree-sha1 = "384ccc9ef660546b438581375d5c2b87fcac3b59"
libc = "glibc"
os = "linux"

    [[libidn2.download]]
    sha256 = "d8a0cdb60bfc967854618564ae499e9c3f3a76b776dde302e7c846b7dcb11825"
    url = "https://github.com/JuliaBinaryWrappers/libidn2_jll.jl/releases/download/libidn2-v2.3.8+0/libidn2.v2.3.8.powerpc64le-linux-gnu.tar.gz"
[[libidn2]]
arch = "riscv64"
git-tree-sha1 = "8e6365f2f39490f8e2736a16c06641b7660eee4e"
libc = "glibc"
os = "linux"

    [[libidn2.download]]
    sha256 = "584f796716c456cf7fad5d26b611356510246fd67c1ed49b616a969a65b94277"
    url = "https://github.com/JuliaBinaryWrappers/libidn2_jll.jl/releases/download/libidn2-v2.3.8+0/libidn2.v2.3.8.riscv64-linux-gnu.tar.gz"
[[libidn2]]
arch = "x86_64"
git-tree-sha1 = "f5ee336fbba4cb4a8ee9d78108c90902d0ec6f83"
os = "macos"

    [[libidn2.download]]
    sha256 = "3bfc2f0cdab7451b9689cc4bdea637884e74dbc80e60acbde440a1c7e2449ad1"
    url = "https://github.com/JuliaBinaryWrappers/libidn2_jll.jl/releases/download/libidn2-v2.3.8+0/libidn2.v2.3.8.x86_64-apple-darwin.tar.gz"
[[libidn2]]
arch = "x86_64"
git-tree-sha1 = "3fb57bf25bc0c133e7f2742a38a04ee135b39a1c"
libc = "glibc"
os = "linux"

    [[libidn2.download]]
    sha256 = "db8eb2ec31975954ff2eabb733a9cdf16c4b013d259f3afa09e2e14d4732c614"
    url = "https://github.com/JuliaBinaryWrappers/libidn2_jll.jl/releases/download/libidn2-v2.3.8+0/libidn2.v2.3.8.x86_64-linux-gnu.tar.gz"
[[libidn2]]
arch = "x86_64"
git-tree-sha1 = "4558bd851f115a34f1ab2d95164ac402b77d2f04"
libc = "musl"
os = "linux"

    [[libidn2.download]]
    sha256 = "03534b6a56037134fd9180763bacc31d5b50e4e042bd9ee33ef846c005d72feb"
    url = "https://github.com/JuliaBinaryWrappers/libidn2_jll.jl/releases/download/libidn2-v2.3.8+0/libidn2.v2.3.8.x86_64-linux-musl.tar.gz"
[[libidn2]]
arch = "x86_64"
git-tree-sha1 = "54c39986d447e82d651ce0b9c4d2a3223db890ac"
os = "freebsd"

    [[libidn2.download]]
    sha256 = "a245c71574057f684280505901c2527084f8bbfe1009b2260e1077c18632c5ae"
    url = "https://github.com/JuliaBinaryWrappers/libidn2_jll.jl/releases/download/libidn2-v2.3.8+0/libidn2.v2.3.8.x86_64-unknown-freebsd.tar.gz"
[[libidn2]]
arch = "x86_64"
git-tree-sha1 = "49bf9b270bfc21d1dcd282ad5cc55c04c977746c"
os = "windows"

    [[libidn2.download]]
    sha256 = "dfce77c4299a5b955a7b09276b485cad90dcbacfa5131a0f6a0c158230ba3c02"
    url = "https://github.com/JuliaBinaryWrappers/libidn2_jll.jl/releases/download/libidn2-v2.3.8+0/libidn2.v2.3.8.x86_64-w64-mingw32.tar.gz"
